# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-20 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=4, unique=True)),
                ('referencias', models.CharField(max_length=30, unique=True)),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
    ]
